packages:
  - sdks/node
  - hsafa-core/core
  - hsafa-core/sdks/service-node
  - hsafa-core/services/test-service
  - hsafa-spaces/server
  - hsafa-spaces/react_app
  - hsafa-spaces/rn_app
  - hsafa-cases
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
