packages:
  - sdks/node
  - hsafa-core/core
  - hsafa-core/sdks/service-node
  - hsafa-core/services/test-service
  - hsafa-spaces/sdks/react-native-sdk
  - hsafa-spaces/rn-app
  - hsafa-spaces/use-case-app
  - hsafa-cases
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
