packages:
  - hsafa-gateway
  - node-sdk
  - react-sdk
  - react-native-sdk
  - rn-app
  - ui-sdk
  - nextjs-test-app
  - use-case-app
  - hsafa-docs
  - vercel-ai-sdk-docs
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
